version: "3"
services:

  jupyter:
     image: jupyter/datascience-notebook
     tty: true
     networks:
       - inbound
     ports:
       - "8888:8888"
     command: sh -c "jupyter-notebook"
     working_dir: /work
     volumes:
      - "./notebooks:/work"


  prefect-agent:
    build: ./prefect-agent
    tty: true
    networks:
      - inbound
    command: sh -c "prefect agent start docker -t <token>"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"





networks:
    inbound:



